version: '3.6'
networks:
  database-stream-changes:
    name: database-stream-changes
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    container_name: zookeeper
    networks:
      - database-stream-changes
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    container_name: kafka
    networks:
      - database-stream-changes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka-connect:
    image: debezium/connect:1.2
    container_name: kafka-connect
    networks:
      - database-stream-changes
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - db
    environment:
      GROUP_ID: "kafka-connect-group"
      BOOTSTRAP_SERVERS: "kafka:29092"
      CONFIG_STORAGE_TOPIC: "kafka-connect-config-topic"
      OFFSET_STORAGE_TOPIC: "kafka-connect-offset-topic"
      STATUS_STORAGE_TOPIC: "kafka-connect-status-topic"
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: db
    networks:
      - database-stream-changes
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "!Password1"
      MSSQL_AGENT_ENABLED: "true"
    volumes:
      - ./setup/sql/db-init.sql:/tmp/init.sql
      - ./setup/sql/active-cdc.sql:/tmp/active-cdc.sql